# Generated by Django 5.0.7 on 2024-07-17 10:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OP', 'Open'), ('PE', 'Pedding'), ('PA', 'Paid'), ('LT', 'Late'), ('CL', 'Canceled')], default='OP', max_length=2)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
