# Generated by Django 5.0.7 on 2024-07-17 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_bills_created_at_bills_due_date_bills_issue_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 17, 9, 4, 39, 297054)),
        ),
        migrations.AlterField(
            model_name='bills',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 17, 9, 4, 39, 297040)),
        ),
    ]
