# Generated by Django 5.0.7 on 2024-07-17 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_alter_bills_due_date_alter_bills_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='bills',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 17, 14, 6, 10, 357718)),
        ),
        migrations.AlterField(
            model_name='bills',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 17, 14, 6, 10, 357658)),
        ),
    ]
