# Generated by Django 5.0.7 on 2024-07-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_alter_bills_created_at_alter_bills_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bills',
            name='issue_date',
            field=models.DateField(),
        ),
    ]
