# Generated by Django 5.0.7 on 2024-07-17 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bills.categories'),
        ),
    ]
