# Generated by Django 5.0.7 on 2024-07-18 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_bills_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='payment_type',
        ),
    ]
