# Generated by Django 5.0.7 on 2024-07-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_remove_bills_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='status',
            field=models.CharField(choices=[('OP', 'Open'), ('PE', 'Pending'), ('PA', 'Paid'), ('LT', 'Late'), ('CL', 'Canceled')], default='OP', max_length=2),
        ),
    ]
