# Generated by Django 5.0.7 on 2024-07-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0009_alter_bills_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
