# Generated by Django 5.0.7 on 2024-07-21 11:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0010_alter_bills_created_at'),
        ('cards', '0011_card_available_limit_alter_card_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bills.categories'),
        ),
        migrations.CreateModel(
            name='CreditCardBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OP', 'Open'), ('PE', 'Pending'), ('PA', 'Paid'), ('LT', 'Late'), ('CL', 'Canceled')], default='OP', max_length=2)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
            ],
        ),
    ]
