# Generated by Django 5.0.7 on 2024-07-24 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0011_alter_bills_category_creditcardbill'),
        ('cards', '0012_alter_card_card_type'),
        ('transactions', '0006_remove_payments_credit_card_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.card'),
        ),
        migrations.AddField(
            model_name='bills',
            name='is_credit_card_bill',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CreditCardBill',
        ),
    ]
