# Generated by Django 5.0.7 on 2024-07-17 03:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0004_alter_card_card_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0)),
                ('account_type', models.CharField(choices=[('SA', 'Savings'), ('CR', 'Current'), ('BO', 'Both'), ('SL', 'Salary')], default='CR', max_length=2)),
                ('bank', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.brand')),
                ('card', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.card')),
            ],
        ),
    ]
