# Generated by Django 5.0.7 on 2024-07-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_created_at_alter_account_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('SA', 'Savings'), ('CR', 'Current'), ('SL', 'Salary'), ('BO', 'Both')], default='CR', max_length=2),
        ),
    ]
