# Generated by Django 5.0.7 on 2024-07-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_created_at'),
        ('cards', '0009_alter_card_created_at_alter_card_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='bank',
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ManyToManyField(blank=True, null=True, to='cards.brand'),
        ),
    ]
