# Generated by Django 5.0.7 on 2024-07-19 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_account_bank_account_bank'),
        ('cards', '0009_alter_card_created_at_alter_card_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='bank',
        ),
        migrations.AlterField(
            model_name='account',
            name='card',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='cards.card'),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateField(auto_created=True, editable=False),
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.brand'),
        ),
    ]
