# Generated by Django 5.0.7 on 2024-07-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_payments_transactionaccounttoaccount_transactions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(choices=[('WD', 'Withdraw'), ('DP', 'Deposit'), ('PX', 'PIX')], default='PX', max_length=2),
        ),
    ]
