# Generated by Django 5.0.7 on 2024-07-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transactions_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='transaction_type',
            field=models.CharField(choices=[('MO', 'Money'), ('TD', 'Ted'), ('PX', 'Pix'), ('CD', 'Credit'), ('DB', 'Debit')], default='MO', max_length=2),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(choices=[('WD', 'Withdraw'), ('DP', 'Deposit'), ('PX', 'PIX')], default='DP', max_length=2),
        ),
    ]
