# Generated by Django 5.0.7 on 2024-07-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_payments_credit_card_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='credit_card_bill',
        ),
        migrations.AlterField(
            model_name='payments',
            name='transaction_type',
            field=models.CharField(choices=[('MO', 'Money'), ('TD', 'Ted'), ('PX', 'Pix'), ('CR', 'Credit'), ('DE', 'Debit')], default='MO', max_length=2),
        ),
    ]
