# Generated by Django 5.0.7 on 2024-07-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_due_date_alter_card_expire_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='due_date',
            new_name='due_day',
        ),
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('DE', 'Debit'), ('CR', 'Credit'), ('BO', 'Both')], default='CR', max_length=2),
        ),
        migrations.AlterField(
            model_name='card',
            name='expire_date',
            field=models.DateField(),
        ),
    ]
