# Generated by Django 5.0.7 on 2024-07-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_rename_due_date_card_due_day_card_card_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('DE', 'Debit'), ('CR', 'Credit'), ('BO', 'Both'), ('BF', 'Benefits')], default='CR', max_length=2),
        ),
    ]
