# Generated by Django 5.0.7 on 2024-07-17 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_card_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='brand',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='cards.brand'),
        ),
    ]
