# Generated by Django 5.0.7 on 2024-07-17 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_card_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='brand',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='cards.brand'),
        ),
    ]
