# Generated by Django 5.0.7 on 2024-07-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_alter_card_created_at_alter_card_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
