# Generated by Django 5.0.7 on 2024-07-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_card_available_limit_alter_card_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('DE', 'Debit'), ('CR', 'Credit'), ('BF', 'Benefits'), ('BO', 'Both')], default='BO', max_length=2),
        ),
    ]
